---
title: ""
---

### Identifying melanoma prognostic biomarkers by integrating imaging data and genetic data


I am conducting research with [Gen Li](https://sites.google.com/view/ligen) at the [Department of Biostatistics at Columbia University](https://www.mailman.columbia.edu/become-student/departments/biostatistics), Yvonne Saenger and Robyn Gartrell from [Columbia University Medical Center](http://www.cumc.columbia.edu/).

My work involved:

1. Creating interactive heat maps and adopting clustering analysis to explore hierarchical structure of melanoma gene expression data.
2. Building predictive model on recurrence using logistic regression with lasso penalty, and validated it on two separate cohorts using cross-validation with bootstrapping.
3.  Communicating results of analyses, modeling, and tests through data visualization, interactive apps, and writing in R Markdown.

Paper in progress. 

### Estimating Influenza Incidence from Diagnostic Codes

This work is mentored by Sasikiran Kandula and [Jeffrey Shaman](http://blogs.cuit.columbia.edu/jls106/) in the [Department of Environmental Health Sciences at Columbia University](https://www.mailman.columbia.edu/become-student/departments/environmental-health-sciences-ehs).

[Slide](https://jiayiji.github.io/P9120-Final-Project-Slide/Final_Project_Slide.html)

1. Analyzed large datasets (~68 million) and explored machine learning methods in MySQL and R  to track real-time influenza incidence combining both diagnostic and virologic data.
2. Compared and Contrasted different machine learning methods (Boosting, SVM, Random Forest...) using cross-validation.
3. Created clear and compelling reports, visualizations, and interactive apps for collaborators in R Markdown.